version: '3'
services:
  mongodb:
    image: mongo
    volumes:
      - data:/data/db
      - ./scripts:/docker-entrypoint-initdb.d:ro
    ports:
      - "27017:27017"
volumes:
  data:
    external: false